context games

diff --git a/debian/ctxfmtutil b/debian/ctxfmtutil
--- a/debian/ctxfmtutil
+++ b/debian/ctxfmtutil
@@ -3,11 +3,21 @@
 # ctxfmtutil
 #
 # This script reads the context format definition file from
-#	/etc/texmf/context/formats.cnf
+#	/etc/texmf/context/config/formats.cnf
 # and creates the necessary formats by calling texexec.
 #
 
-export TEXMFSYSCONFIG=/usr/share/texmf
+configfile=/etc/texmf/context/config/formats.cnf
+
+texmfsysvar=$(kpsewhich -expand-var '$TEXMFSYSVAR')
+texmfvar=$(kpsewhich -expand-var '$TEXMFVAR')
+
+if [ "$(id -u)" -eq 0 ] ; then
+  TEXFORMATS=$texmfsysvar/web2c
+else
+  TEXFORMATS=$texmfvar/web2c
+fi
+export TEXFORMATS
 
 case "$1" in 
   "--build")
@@ -18,14 +28,30 @@ case "$1" in
   	echo "Wrong commandline argument $1!" >&2 ; exit 1 ;;
 esac
 
+
+dhit_build_format ()
+{
+    tempfile=$(mktemp -p /tmp ctxfmtutil.XXXXXXXX)
+    printf "Building ConTeXt format(s) $2 with engine $1.\n\tThis may take some time... "
+    if texexec --fast --make --$1 $2 > $tempfile 2>&1 ; then
+        rm -f $tempfile
+        echo "done."
+    else
+        echo
+        echo "texexec failed. Output has been stored in"
+        echo "$tempfile"
+        echo "Please include this file if you report a bug."
+        echo
+        exit 1
+    fi
+}
+
+
 remove_format_files()
 {
   engine=$1
   format=$2
   if [ "$engine" = pdftex ] ; then engine=pdfetex ; fi
-  case "$format" in 
-    ??) format=cont-$format ;;
-  esac
   rm -f $TEXMFSYSCONFIG/web2c/$engine/$format.*
 }
 
@@ -39,8 +65,11 @@ parse_line()
   allformats="$@"
   for e in $allengines ; do
     for f in $allformats ; do
+      case "$f" in
+        ??) format=cont-$format ;;
+      esac
       if [ $build = 1 ] ; then
-        texexec --fast --make --$e $f
+        dhit_build_format $e $f
       else
         remove_format_files $e $f
       fi
@@ -51,7 +80,7 @@ parse_line()
 OIFS=$IFS
 IFS='
 '
-set $(echo x; sed '/^#/d; /^[  ]*$/d' "/etc/texmf/context/formats.cnf") ; shift
+set $(echo x; sed '/^#/d; /^[  ]*$/d' "$configfile") ; shift
 IFS=$OIFS
 for line 
 do
