Context: * new upstream release * pre-build format based on xetex (Closes: #483885) * depend on luatex >= 0.45.0 (Closes: #529570)

diff --git a/debian/make-orig-tar b/debian/make-orig-tar
--- a/debian/make-orig-tar
+++ b/debian/make-orig-tar
@@ -22,29 +22,34 @@ if [ "$1" = "-p" ] ; then
 	getnet=0
 fi
 
+if [ -n "$1" ] ; then
+	version="$1"
+fi
+
 toplevel=$(pwd)
 dh_testdir
 
 TMPDIR=$(mktemp -d)
 cd $TMPDIR
 
-echo -n "Checking version ... "
-# wget $WGETQUIET -O foo.html http://wiki.contextgarden.net/Release_Notes
-# version=$(egrep 'title="Context [0-9]{4}\.[0-9]{2}\.[0-9]{2}">' foo.html | sed -e 's/^.*Context \([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)">.*$/\1.\2.\3/')
+if [ -n "$version" ] ; then
+	echo "Using version from command line: $version"
+else
+	echo -n "Checking version ... "
+	# wget $WGETQUIET -O foo.html http://wiki.contextgarden.net/Release_Notes
+	# version=$(egrep 'title="Context [0-9]{4}\.[0-9]{2}\.[0-9]{2}">' foo.html | sed -e 's/^.*Context \([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)">.*$/\1.\2.\3/')
 
-wget $WGETQUIET -O foo.html http://www.pragma-ade.com/download-1.htm
-version=$(w3m -dump foo.html | grep cont-tmf.zip | sed -e 's/^.*distribution[ \t]*\([0-9]*\)-\([0-9]*\)-\([0-9]*\) .*$/\1.\2.\3/')
-case "$version" in
-	????.??.??)	echo "$version" ;;
-	*)		echo "Can't get version, exiting!"; exit 1 ;;
-esac
+	wget $WGETQUIET -O foo.html http://www.pragma-ade.com/download-1.htm
+	version=$(w3m -dump foo.html | grep cont-tmf.zip | sed -e 's/^.*distribution[ \t]*\([0-9]*\)-\([0-9]*\)-\([0-9]*\) .*$/\1.\2.\3/')
+	case "$version" in
+		????.??.??)	echo "$version" ;;
+		*)		echo "Can't get version, exiting!"; exit 1 ;;
+	esac
+fi
 
 if [ $getnet = 1 ] ; then
 	echo -n "Getting cont-tmf.zip ..."
 	wget $WGETQUIET http://www.pragma-ade.com/context/current/cont-tmf.zip
-	echo "done"
-	echo -n "Getting cont-fnt.zip ..."
-	wget $WGETQUIET http://www.pragma-ade.com/context/current/cont-fnt.zip
 	echo "done"
 	echo -n "Getting cont-img.zip ..."
 	wget $WGETQUIET http://www.pragma-ade.com/context/current/cont-img.zip
@@ -53,7 +58,7 @@ if [ $getnet = 1 ] ; then
 	wget $WGETQUIET http://www.pragma-ade.com/context/current/cont-ext.zip
 	echo "done"
 else
-	for i in cont-tmf.zip cont-fnt.zip cont-img.zip cont-ext.zip ; do
+	for i in cont-tmf.zip cont-img.zip cont-ext.zip ; do
 		if ! [ -r "$srcdir/$i" ] ; then
 			echo "File not found: $srcdir/$i!" 
 			echo "Exiting!"
@@ -69,7 +74,7 @@ mkdir context-nonfree-$version
 cnf="$TMPDIR/context-nonfree-$version"
 
 cd context-$version
-for i in cont-tmf.zip cont-fnt.zip cont-img.zip cont-ext.zip ; do
+for i in cont-tmf.zip cont-img.zip cont-ext.zip ; do
 	echo -n "Unzipping $i ..."
 	if [ $getnet = 1 ] ; then
 		unzip $UNZIPQUIET ../$i
